"""add_pixel_image_svg_to_souvenirs

Revision ID: d36f54e832d2
Revises: 2a349288b005
Create Date: 2025-12-02 11:26:53.845884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36f54e832d2'
down_revision: Union[str, None] = '2a349288b005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souvenirs', sa.Column('pixel_image_svg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('souvenirs', 'pixel_image_svg')
    # ### end Alembic commands ###

